<?php
/**
 * @file
 * A Google Auth module
 */

/**
 * Implements hook_block_info()
 */
function mkGoogleAuth_block_info() {
  $blocks['googleAuth'] = array(
    'info' => t('Google Login'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function mkGoogleAuth_block_view($delta = '') {
  global $user;
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'googleAuth':
      if (!empty($user->uid)) {
        continue;
      }
      $form = drupal_get_form('frmGoogleAuthLogin');
      $block['subject'] = t('Google Login');
      $block['content'] = $form; //"<a class='login' href='#'><img src=\"http://mkgalaxy.com/api/googleauth/google-login-button-asif18.png\" alt=\"Google login\" title=\"login with google\" style='width:100%;' /></a>";
      break;
  }
  return $block;
}

function frmGoogleAuthLogin($form, &$form_state)
{
  $form['frm_google_auth'] = array(
    '#type' => 'image_button',
    '#src' => 'http://mkgalaxy.com/api/googleauth/google-login-button-asif18.png',
    '#attributes' => array('class' => array('customFromImageButton')),
  );

  return $form;
}
function mkGoogleAuth_form_alter(&$form, &$form_state, $form_id) {
echo $form_id;exit;
  if ($form_id = 'frmGoogleAuthLogin') {
    $form['actions']['frm_google_auth']['#attributes']['class'][] = 'form-submitone';
  }
}
function frmGoogleAuthLogin_validate($form, &$form_state) {

  return true;
}
function frmGoogleAuthLogin_submit($form, &$form_state) {
echo 'form submitted';
exit;
}